[endeavour]
alias = "endeavouros"
margin = [2, 0, 0,]
art    = [
"{RD}                     ./{MA}o{BE}.               ",
"{RD}                   ./{MA}sssso{BE}-             ",
"{RD}                 `:{MA}osssssss+{BE}-           ",
"{RD}               `:+{MA}sssssssssso{BE}/.         ",
"{RD}             `-/o{MA}ssssssssssssso{BE}/.       ",
"{RD}           `-/+{MA}sssssssssssssssso{BE}+:`     ",
"{RD}         `-:/+{MA}sssssssssssssssssso{BE}+/.    ",
"{RD}       `.://o{MA}sssssssssssssssssssso{BE}++-   ",
"{RD}      .://+{MA}ssssssssssssssssssssssso{BE}++:  ",
"{RD}    .:///o{MA}ssssssssssssssssssssssssso{BE}++: ",
"{RD}  `:////{MA}ssssssssssssssssssssssssssso{BE}+++.",
"{RD}`-////+{MA}ssssssssssssssssssssssssssso{BE}++++-",
"{RD} `..-+{MA}oosssssssssssssssssssssssso{BE}+++++/`",
"{BE}   ./++++++++++++++++++++++++++++++/:.  ",
"{BE}  `:::::::::::::::::::::::::------``    "
]
[arch]
alias = "default"
margin = [0, 0, 0,]
art = [
"{BE}                   -`                 ",
"{BE}                  .o+`                ",
"{BE}                 `ooo/                ",
"{BE}                `+oooo:               ",
"{BE}               `+oooooo:              ",
"{BE}               -+oooooo+:             ",
"{BE}             `/:-:++oooo+:            ",
"{BE}            `/++++/+++++++:           ",
"{BE}           `/++++++++++++++:          ",
"{BE}          `/+++ooooooooooooo/`        ",
"{BE}         ./ooosssso++osssssso+`       ",
"{BE}        .oossssso-````/ossssss+`      ",
"{BE}       -osssssso.      :ssssssso.     ",
"{BE}      :osssssss/        osssso+++.    ",
"{BE}     /ossssssss/        +ssssooo/-    ",
"{BE}   `/ossssso+/:-        -:/+osssso+-  ",
"{BE}  `+sso+:-`                 `.-/+oso: ",
"{BE} `++:.                           `-/+/",
"{BE} .`                                 ` ",
]
