[manager]
ratio = [1, 3, 3]
show_hidden = true

[opener]
edit = [{ run = "nvim $0", block = true }]

[plugin]
code = "bat"
json = "bat"
prepend_previewers = [
  { mime = "text/csv", run = "miller" },
  { name = "*.md", run = "glow" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
