[theme]
background = "#303446"
primary = "#c6d0f5"
secondary = "#81c8be"
title = "#babbf1"
playing = "#a6d189"
playing_bg = "#303446"
highlight = "#c6d0f5"
highlight_bg = "#75779b"
playing_selected = "#a6d189"
error = "#303446"
error_bg = "#e78284"
statusbar = "#babbf1"
statusbar_bg = "#414559"
statusbar_progress = "#babbf1"
cmdline = "#babbf1"
cmdline_bg = "#292c3c"
