shell /usr/bin/fish -l
font_family Maple Mono
font_size 14

map alt+t new_tab
map alt+h previous_tab
map alt+l next_tab

map alt+k scroll_line_up
map alt+j scroll_line_down
map ctrl+alt+b scroll_page_up
map ctrl+alt+f scroll_page_down

map alt+- launch --location=vsplit
map alt+\ launch --location=hsplit
map ctrl+h previous_window
map ctrl+k previous_window
map ctrl+l next_window
map ctrl+j next_window

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         angled
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
